spring:
  datasource:
    #springboot的数据源配置默认是org.apache.tomcat.jdbc.pool.DataSource
    #修改默认配置为阿里巴巴Druid连接池
    #驱动配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: root

    #连接池配置信息
    initialSize: 5
    minIdel: 5
    maxActive: 20

    # 配置获取连接超时等待时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
    timeBetweenEvictionRunsMillis: 60000

    #配置一个连接池在池中的最小生存时间，单位毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat=true

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5Dialet

  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: ylwl
    pool:
      max-wait: -1
      min-idle: 0
      max-active: 8
      max-idle: 8


